#https://drive.google.com/uc?id=
category_map = {
    "News_and_Media": {"bottom": "https://i.ibb.co/ZLHYYk5/img-bottom.jpg", "modal": "https://i.ibb.co/tKpGWkS/img-modal.jpg", "right": "https://i.ibb.co/Qvzj9Fn/img-right.jpg"},
    "Food_and_Drink": {"bottom": "https://i.ibb.co/FJ33jQ0/img-bottom.jpg", "modal": "https://i.ibb.co/9vYp1zK/img-modal.jpg", "right": "https://i.ibb.co/jyPbK1L/image-right.jpg"},
    "Arts_and_Entertainment": {"bottom": "https://i.ibb.co/pR573Rn/Arts-and-Entertainment-bottom.jpg",
                       "modal": "https://i.ibb.co/12G3xyZ/Arts-and-Entertainment-modal.jpg",
                       "right": "https://i.ibb.co/54cpnq0/Arts-and-Entertainment-right.jpg"},
    "Business_and_Industry": {"bottom": "https://i.ibb.co/HC1JWRJ/Business-and-Industry-bottom.jpg",
                       "modal": "https://i.ibb.co/XFHWyBf/Business-and-Industry-modal.jpg",
                       "right": "https://i.ibb.co/zRjWp51/Business-and-Industry-right.jpg"},
    "Travel": {"bottom": "https://i.ibb.co/RzS9Jdx/Travel-bottom.jpg",
                       "modal": "https://i.ibb.co/GxSR6gY/Travel-modal.jpg",
                       "right": "https://i.ibb.co/pfpVFw8/Travel-right.jpg"},
    "Health": {"bottom": "https://i.ibb.co/Fhmf4rt/Health-bottom.jpg",
                       "modal": "https://i.ibb.co/0BssyQQ/Health-modal.jpg",
                       "right": "https://i.ibb.co/pQbs4dD/Health-right.jpg"},
    "Sports": {"bottom": "https://i.ibb.co/vvVqX5G/Sports-bottom.jpg",
                       "modal": "https://i.ibb.co/K7N0ZWR/Sports-modal.jpg",
                       "right": "https://i.ibb.co/6ttNXD1/Sports-right.jpg"},
    "Autos_and_Vehicles": {"bottom": "https://i.ibb.co/wLMnDgy/Autos-and-Vehicles-bottom.jpg",
                       "modal": "https://i.ibb.co/fN5QR7c/Autos-and-Vehicles-modal.jpg",
                       "right": "https://i.ibb.co/B3bRsbb/Autos-and-Vehicles-right.jpg"},
    "Games": {"bottom": "https://i.ibb.co/N6PjZFT/Games-bottom.jpg",
                       "modal": "https://i.ibb.co/N6Jgbgr/Games-modal.jpg",
                       "right": "https://i.ibb.co/tKqwFd9/Games-right.jpg"},
    "Tech": {"bottom": "https://i.ibb.co/qDc5QHn/Tech-bottom.jpg",
                       "modal": "https://i.ibb.co/6Hd64GM/Tech-modal.jpg",
                       "right": "https://i.ibb.co/sJHkMtd/Tech-right.jpg"},

}

categories_keywords = {
    "News_and_Media": [
        "news",
        "media",
        "headlines",
        "breaking news",
        "newspaper",
        "magazine",
        "editorial",
        "broadcast",
        "journalism",
        "reporter",
        "anchor",
        "coverage",
        "press release",
        "press conference",
        "online news",
        "radio news",
        "television news",
        "newsletter",
        "opinion piece",
        "news agency",
        "wire service",
        "BBC",
        "CNN",
        "Reuters",
        "AP",
        "Bloomberg",
        "Fox News",
        "news feed",
        "publishing",
        "columnist",
        "press freedom",
        "live coverage",
        "news bulletin",
        "investigative reporting",
        "news network",
        "tabloid",
        "multimedia",
        "breaking story",
        "news aggregator",
        "wire report",
        "fact-check",
        "photojournalism",
        "editorial board",
        "reportage",
        "audio news",
        "press pass",
        "media outlet",
        "digital media",
        "news cycle",
        "cover story",
        "public broadcasting"
    ],
    "Arts_and_Entertainment": [
        "art",
        "entertainment",
        "cinema",
        "film",
        "movie",
        "theater",
        "music",
        "concert",
        "gallery",
        "museum",
        "performance",
        "exhibition",
        "dance",
        "painting",
        "sculpture",
        "ballet",
        "opera",
        "musical",
        "play",
        "comedy",
        "drama",
        "festival",
        "circus",
        "magic show",
        "puppet show",
        "street art",
        "graphic design",
        "digital art",
        "photography",
        "stand-up comedy",
        "entertainment news",
        "celebrity gossip",
        "awards show",
        "Oscars",
        "Grammys",
        "Broadway",
        "Hollywood",
        "indie film",
        "art history",
        "pop culture",
        "variety show",
        "performance art",
        "installation art",
        "fine art",
        "literature",
        "poetry",
        "artist studio",
        "cultural event",
        "art workshop",
        "craft fair"
    ],
    "Business_and_Industry": [
        "business",
        "industry",
        "corporate",
        "entrepreneurship",
        "startup",
        "merger",
        "acquisition",
        "joint venture",
        "management",
        "leadership",
        "finance",
        "marketing",
        "advertising",
        "sales",
        "branding",
        "human resources",
        "supply chain",
        "logistics",
        "e-commerce",
        "manufacturing",
        "production",
        "economy",
        "stock market",
        "trading",
        "investment",
        "venture capital",
        "angel investor",
        "business plan",
        "business model",
        "B2B",
        "B2C",
        "wholesale",
        "retail",
        "consulting",
        "business strategy",
        "market research",
        "profit",
        "revenue",
        "ROI",
        "benchmarking",
        "outsourcing",
        "compliance",
        "trade show",
        "conference",
        "franchise",
        "small business",
        "executive",
        "board of directors",
        "stakeholder",
        "customer relations"
    ],
    "Travel": [
        "travel",
        "tourism",
        "vacation",
        "holiday",
        "trip",
        "tour",
        "itinerary",
        "passport",
        "visa",
        "flight",
        "airline",
        "hotel",
        "hostel",
        "accommodation",
        "resort",
        "cruise",
        "road trip",
        "tourist attraction",
        "landmark",
        "travel agency",
        "travel insurance",
        "travel guide",
        "travel tips",
        "budget travel",
        "luxury travel",
        "backpacking",
        "adventure travel",
        "ecotourism",
        "business travel",
        "cultural travel",
        "travel blog",
        "travel photography",
        "travel vlog",
        "souvenir",
        "car rental",
        "booking",
        "airbnb",
        "travel deals",
        "travel itinerary",
        "solo travel",
        "group tour",
        "sightseeing",
        "destination",
        "globetrotter",
        "jet lag",
        "frequent flyer",
        "travel visa",
        "travel safety",
        "tourism board",
        "local cuisine"
    ],
    "Health": [
        "health",
        "wellness",
        "fitness",
        "nutrition",
        "exercise",
        "diet",
        "vitamins",
        "supplements",
        "mental health",
        "therapy",
        "counseling",
        "hygiene",
        "public health",
        "medical care",
        "doctor",
        "nurse",
        "hospital",
        "clinic",
        "health insurance",
        "disease",
        "infection",
        "virus",
        "chronic illness",
        "prevention",
        "vaccination",
        "immunization",
        "pharmacy",
        "over-the-counter",
        "prescription",
        "pharmaceutical",
        "yoga",
        "meditation",
        "mindfulness",
        "healthy lifestyle",
        "weight loss",
        "BMI",
        "blood pressure",
        "cholesterol",
        "diabetes",
        "cardiology",
        "oncology",
        "dental care",
        "skin care",
        "herbal remedy",
        "alternative medicine",
        "homeopathy",
        "holistic health",
        "rehabilitation",
        "medical research",
        "mental wellbeing"
    ],
    "Sports": [
        "sports",
        "football",
        "soccer",
        "basketball",
        "baseball",
        "tennis",
        "golf",
        "cricket",
        "rugby",
        "hockey",
        "volleyball",
        "swimming",
        "athletics",
        "track and field",
        "gymnastics",
        "boxing",
        "MMA",
        "martial arts",
        "wrestling",
        "cycling",
        "running",
        "marathon",
        "triathlon",
        "skiing",
        "snowboarding",
        "surfing",
        "skateboarding",
        "Olympics",
        "World Cup",
        "sports news",
        "sportsmanship",
        "tournament",
        "league",
        "championship",
        "team sports",
        "individual sports",
        "sports gear",
        "sports equipment",
        "fitness training",
        "coach",
        "sports medicine",
        "referee",
        "umpire",
        "stadium",
        "fan",
        "tailgating",
        "fantasy sports",
        "draft",
        "sports analytics",
        "varsity"
    ],
    "Food_and_Drink": [
        "food",
        "drink",
        "cuisine",
        "recipe",
        "cooking",
        "baking",
        "restaurant",
        "cafe",
        "bar",
        "pub",
        "fast food",
        "fine dining",
        "gourmet",
        "pastry",
        "dessert",
        "beverage",
        "coffee",
        "tea",
        "wine",
        "beer",
        "cocktail",
        "mocktail",
        "smoothie",
        "health food",
        "vegan",
        "vegetarian",
        "gluten-free",
        "paleo",
        "keto",
        "kitchen",
        "catering",
        "delivery",
        "takeout",
        "chef",
        "menu",
        "food blog",
        "food festival",
        "street food",
        "culinary",
        "flavor",
        "spice",
        "condiment",
        "groceries",
        "farmers market",
        "meal prep",
        "nutrition facts",
        "food safety",
        "food truck",
        "food critic",
        "food photography"
    ],
    "Autos_and_Vehicles": [
        "automobile",
        "vehicle",
        "car",
        "truck",
        "SUV",
        "motorcycle",
        "van",
        "electric vehicle",
        "hybrid",
        "sedan",
        "coupe",
        "convertible",
        "minivan",
        "sports car",
        "luxury car",
        "diesel",
        "petrol",
        "car dealership",
        "auto repair",
        "mechanic",
        "car insurance",
        "car finance",
        "lease",
        "rental car",
        "used car",
        "auto parts",
        "car accessories",
        "tire",
        "engine",
        "transmission",
        "car maintenance",
        "oil change",
        "tune-up",
        "brakes",
        "car wash",
        "car detailing",
        "roadside assistance",
        "automotive news",
        "motor show",
        "driving",
        "license",
        "car crash",
        "safety features",
        "GPS navigation",
        "test drive",
        "car loan",
        "car warranty",
        "fleet management",
        "trucking",
        "car performance"
    ],
    "Games": [
        "games",
        "video games",
        "board games",
        "card games",
        "puzzles",
        "PC gaming",
        "console gaming",
        "mobile gaming",
        "esports",
        "multiplayer",
        "singleplayer",
        "RPG",
        "MMORPG",
        "strategy game",
        "shooter game",
        "action game",
        "adventure game",
        "platformer",
        "sports game",
        "racing game",
        "simulation game",
        "sandbox game",
        "puzzle game",
        "casual game",
        "virtual reality",
        "augmented reality",
        "tabletop gaming",
        "dice games",
        "miniatures",
        "game console",
        "Nintendo",
        "PlayStation",
        "Xbox",
        "Steam",
        "GOG",
        "indie games",
        "game development",
        "game design",
        "gamer community",
        "Twitch streaming",
        "live streaming",
        "competitive gaming",
        "leaderboard",
        "gaming tournament",
        "LAN party",
        "game server",
        "beta testing",
        "downloadable content",
        "game mods"
    ],
    "Tech": [
        "technology",
        "tech news",
        "gadgets",
        "software",
        "hardware",
        "programming",
        "coding",
        "AI",
        "artificial intelligence",
        "machine learning",
        "robotics",
        "automation",
        "IoT",
        "internet of things",
        "cloud computing",
        "big data",
        "data science",
        "blockchain",
        "cryptocurrency",
        "web development",
        "mobile apps",
        "startups",
        "innovation",
        "cybersecurity",
        "networking",
        "servers",
        "databases",
        "operating systems",
        "virtualization",
        "5G",
        "wireless",
        "wearables",
        "augmented reality",
        "virtual reality",
        "quantum computing",
        "tech support",
        "tech industry",
        "tech blog",
        "open source",
        "software engineering",
        "computer science",
        "electronic devices",
        "smartphone",
        "laptop",
        "desktop",
        "tablet",
        "tech conference",
        "firmware",
        "gadget review"
    ]
}
